name: FastAPI CI/CD

on:
  #Trigger workflow
  push:
    branches: main

jobs:
  CI:
    runs-on: ubuntu-lastest
    steps:
      - uses: actions/checkout@v2
        # Step 1: setup python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Install Python Virtual ENV
        run: pip3 install virtualenv

        # Step 3 Virtual ENV
      - name: Virtual ENV
        uses: actions/cache@v2
        id: cache-venv
        with:
          path: venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt')}}
          restore-keys: /
            ${{ runner.os }}-venv-
        # Step 4
      - name: Activate Virtual ENV
        run: python -m venv venv && source venv/bin/activat && pip3 install -r requirements.txt

      - name: Run Tests
        run: . venv/bin/activate && pytest
      - name: Create archive of dependencies
        run: /
          cd ./venv/lib/python3.10/site-packages
          zip -r9 ../../../../api.zip .
      - name: Add API files to Zip file
        run: cd ./api && zip -g ../api.zip -r .
      - name: Upload zip file artifact
        uses: actions/upload-artifact@v2
        with:
          name: api
          path: api.zip
